swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: 1.0.0
  termsOfService: http://swagger.io/terms/
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: "#/definitions/Login"
      produces:
        - application/json
      responses:
        "200":
          description: Login Successfully
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: "#/definitions/User"
      produces:
        - application/json
      responses:
        "200":
          description: Signup Successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: "#/definitions/UserProfile"
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /transactions/{startDate}/{endDate}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: User Month Transactions
      description: See the month user transactions
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: startDate
          description: first day of research
          type: string
          required: true
          format: DD/MM
        - in: path
          name: endDate
          description: last day of research
          type: string
          required: true
          format: DD/MM
        - in: body
          name: Account id
          description: Id Of Selected Account
          required: true
          schema:
            $ref: "#/definitions/MonthTransactions"

      produces:
        - application/json
      responses:
        "200":
          description: User month transactions retrieved successully
          schema:
            type: object
            properties:
              body:
                type: object
                properties:
                  transaction:
                    type: array
                    items:
                      $ref: "#/definitions/MonthTransactionsResponse"

        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /transactions/{transactionId}/details:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction
      summary: Transaction Details
      description: See the month user transactions in details
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: transactionId
          type: integer
          required: true
          description: Numeric ID of the account to get
      produces:
        - application/json
      responses:
        "200":
          description: User month details transactions retrieved successully
          schema:
            $ref: "#/definitions/MonthTransactionsResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    patch:
      security:
        - Bearer: []
      tags:
        - Transaction Details
      summary: Add Or Edit A Note Or Category
      description: Add Or Edit A Note Or Category To His Transaction Details
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          name: transactionId
          type: integer
          required: true
          description: Numeric ID of the account for add or modif a note
        - in: body
          name: Add Or Edit A Note Or Category
          description: Add or edit a note or category in transaction details
          required: true
          schema:
            $ref: "#/definitions/AddDetails"
      produces:
        - application/json
      responses:
        "200":
          description: details transactions with add or edit notes or category  successfully
          schema:
            $ref: "#/definitions/MonthTransactionsResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

    delete:
      security:
        - Bearer: []
      tags:
        - Transaction Details
      summary: Delete Note And Category
      description: User delete note and category to his transaction details
      parameters:
        - in: path
          name: transactionId
          type: integer
          required: true
          description: transaction ID to delete details
      produces:
        - application/json
      responses:
        "200":
          description: delete details retrieved successully
          schema:
            type: object
            properties:
              deleted:
                type: boolean

        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  MonthTransactions:
    type: object
    properties:
      id:
        type: number
  MonthTransactionsResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          date:
            type: string
          decription:
            type: string
          amount:
            type: number
          balance:
            type: number
          transactionType:
            type: string
          categoryFood:
            type: string
          notes:
            type: string
  AddDetails:
    type: object
    properties:
      body:
        type: object
        properties:
          categoryFood:
            type: string
          notes:
            type: string
